os: windows
language: shell
script:
- choco install autoit.portable
- ./build.sh
deploy:
  provider: releases
  api_key: $API_KEY
  file: "time-tracker.zip"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- travis_terminate 0